package org.en.tealEye.printing.gui;

import org.en.tealEye.printing.controller.FieldMapper;
import org.en.tealEye.guiExt.ExtPanel.ExtendedJPanel;
import org.en.tealEye.guiExt.ExtPanel.ExtendedJPanelImpl;

import java.util.ResourceBundle;
import java.util.List;
import java.lang.reflect.Field;

/**
 *
 * @author Stephan Pudras
 */
public class EnvelopePrintFrame extends javax.swing.JFrame {

    /** Creates new form EnvelopePrintFrame */
    public EnvelopePrintFrame() {

                 initComponents();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        toolPanel = new ExtendedJPanelImpl();
        epHAddressLoc = new javax.swing.JSpinner();
        epVAddressLoc = new javax.swing.JSpinner();
        epHSenderLoc = new javax.swing.JSpinner();
        epVSenderLoc = new javax.swing.JSpinner();
        epHGraphicLoc = new javax.swing.JSpinner();
        epVGraphicLoc = new javax.swing.JSpinner();
        epAddressFontBt = new javax.swing.JButton();
        epSenderFontBt = new javax.swing.JButton();
        epGraphicBt = new javax.swing.JButton();
        epGraphicCheckBox = new javax.swing.JCheckBox();
        epEnvelopeType = new javax.swing.JComboBox();
        epEnvelopeAxis = new javax.swing.JComboBox();
        enSenderCheckBox = new javax.swing.JCheckBox();
        epPrintBt = new javax.swing.JButton();
        epDeclineBt = new javax.swing.JButton();
        epFowardBt = new javax.swing.JButton();
        epHomeBt = new javax.swing.JButton();
        epBackwardBt = new javax.swing.JButton();
        epHAddressLabel = new javax.swing.JLabel();
        epVAddressLabel = new javax.swing.JLabel();
        epHSenderLabel = new javax.swing.JLabel();
        epVSenderLabel = new javax.swing.JLabel();
        epHGraphicLabel = new javax.swing.JLabel();
        epVGraphicLabel = new javax.swing.JLabel();
        epEnvAxisLabel = new javax.swing.JLabel();
        epEnvTypeLabel = new javax.swing.JLabel();
        epAddressFontPreviewTB = new javax.swing.JTextField();
        epSenderFontPreviewTB = new javax.swing.JTextField();
        epGraphicPathTB = new javax.swing.JTextField();
        epSenderLocCornerRB = new javax.swing.JRadioButton();
        epSenderLocLineRB = new javax.swing.JRadioButton();
        epCount = new javax.swing.JSpinner();
        epCountLabel = new javax.swing.JLabel();
        epOrderTable = new javax.swing.JRadioButton();
        epOrderTeam = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        previewPanel = new ExtendedJPanelImpl();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.6);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        jScrollPane1.setViewportView(toolPanel);

        toolPanel.setMinimumSize(new java.awt.Dimension(1024, 200));
        toolPanel.setName("toolPanel"); // NOI18N
        toolPanel.setPreferredSize(new java.awt.Dimension(1024, 200));
        toolPanel.setRequestFocusEnabled(false);
        toolPanel.setLayout(new java.awt.GridBagLayout());

        epHAddressLoc.setMinimumSize(new java.awt.Dimension(50, 20));
        epHAddressLoc.setName("epHAddressLoc"); // NOI18N
        epHAddressLoc.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epHAddressLoc, gridBagConstraints);

        epVAddressLoc.setMinimumSize(new java.awt.Dimension(50, 20));
        epVAddressLoc.setName("epVAddressLoc"); // NOI18N
        epVAddressLoc.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epVAddressLoc, gridBagConstraints);

        epHSenderLoc.setMinimumSize(new java.awt.Dimension(50, 20));
        epHSenderLoc.setName("epHSenderLoc"); // NOI18N
        epHSenderLoc.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epHSenderLoc, gridBagConstraints);

        epVSenderLoc.setMinimumSize(new java.awt.Dimension(50, 20));
        epVSenderLoc.setName("epVSenderLoc"); // NOI18N
        epVSenderLoc.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epVSenderLoc, gridBagConstraints);

        epHGraphicLoc.setMinimumSize(new java.awt.Dimension(50, 20));
        epHGraphicLoc.setName("epHGraphicLoc"); // NOI18N
        epHGraphicLoc.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epHGraphicLoc, gridBagConstraints);

        epVGraphicLoc.setMinimumSize(new java.awt.Dimension(50, 20));
        epVGraphicLoc.setName("epVGraphicLoc"); // NOI18N
        epVGraphicLoc.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epVGraphicLoc, gridBagConstraints);



        ResourceBundle resourceMap = ResourceBundle.getBundle("org.en.tealEye.resources.EnvelopePrintFrame");
        epAddressFontBt.setText(resourceMap.getString("epAddressFontBt.text")); // NOI18N
        epAddressFontBt.setToolTipText(resourceMap.getString("epAddressFontBt.toolTipText")); // NOI18N
        epAddressFontBt.setName("epAddressFontBt"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epAddressFontBt, gridBagConstraints);

        epSenderFontBt.setText(resourceMap.getString("epSenderFontBt.text")); // NOI18N
        epSenderFontBt.setToolTipText(resourceMap.getString("epSenderFontBt.toolTipText")); // NOI18N
        epSenderFontBt.setName("epSenderFontBt"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epSenderFontBt, gridBagConstraints);

        epGraphicBt.setText(resourceMap.getString("epGraphicBt.text")); // NOI18N
        epGraphicBt.setToolTipText(resourceMap.getString("epGraphicBt.toolTipText")); // NOI18N
        epGraphicBt.setName("epGraphicBt"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epGraphicBt, gridBagConstraints);

        epGraphicCheckBox.setText(resourceMap.getString("epGraphicCheckBox.text")); // NOI18N
        epGraphicCheckBox.setToolTipText(resourceMap.getString("epGraphicCheckBox.toolTipText")); // NOI18N
        epGraphicCheckBox.setName("epGraphicCheckBox"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epGraphicCheckBox, gridBagConstraints);

        epEnvelopeType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DIN C3   324 × 458", "DIN E4   280 × 400", "DIN B4   250 × 353", "DIN C4   229 × 324", "DIN B5   176 × 250", "DIN C5   162 × 229", "DIN C5/6   114 x 229", "DIN DL C5/6   110 × 220", "DIN B6   125 × 176", "DIN C6   114 × 162" }));
        epEnvelopeType.setMinimumSize(new java.awt.Dimension(150, 20));
        epEnvelopeType.setName("epEnvelopeType"); // NOI18N
        epEnvelopeType.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        toolPanel.add(epEnvelopeType, gridBagConstraints);

        epEnvelopeAxis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Horizontal", "Vertikal" }));
        epEnvelopeAxis.setToolTipText(resourceMap.getString("epEnvelopeAxis.toolTipText")); // NOI18N
        epEnvelopeAxis.setMinimumSize(new java.awt.Dimension(150, 20));
        epEnvelopeAxis.setName("epEnvelopeAxis"); // NOI18N
        epEnvelopeAxis.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        toolPanel.add(epEnvelopeAxis, gridBagConstraints);

        enSenderCheckBox.setText(resourceMap.getString("enSenderCheckBox.text")); // NOI18N
        enSenderCheckBox.setToolTipText(resourceMap.getString("enSenderCheckBox.toolTipText")); // NOI18N
        enSenderCheckBox.setName("enSenderCheckBox"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(enSenderCheckBox, gridBagConstraints);

        epPrintBt.setMnemonic(1);
        epPrintBt.setText(resourceMap.getString("epPrintBt.text")); // NOI18N
        epPrintBt.setToolTipText(resourceMap.getString("epPrintBt.toolTipText")); // NOI18N
        epPrintBt.setName("epPrintBt"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        toolPanel.add(epPrintBt, gridBagConstraints);

        epDeclineBt.setMnemonic(1);
        epDeclineBt.setText(resourceMap.getString("epDeclineBt.text")); // NOI18N
        epDeclineBt.setToolTipText(resourceMap.getString("epDeclineBt.toolTipText")); // NOI18N
        epDeclineBt.setName("epDeclineBt"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        toolPanel.add(epDeclineBt, gridBagConstraints);

        epFowardBt.setText(resourceMap.getString("epFowardBt.text")); // NOI18N
        epFowardBt.setToolTipText(resourceMap.getString("epFowardBt.toolTipText")); // NOI18N
        epFowardBt.setName("epFowardBt"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epFowardBt, gridBagConstraints);

        epHomeBt.setText(resourceMap.getString("epHomeBt.text")); // NOI18N
        epHomeBt.setToolTipText(resourceMap.getString("epHomeBt.toolTipText")); // NOI18N
        epHomeBt.setName("epHomeBt"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epHomeBt, gridBagConstraints);

        epBackwardBt.setText(resourceMap.getString("epBackwardBt.text")); // NOI18N
        epBackwardBt.setToolTipText(resourceMap.getString("epBackwardBt.toolTipText")); // NOI18N
        epBackwardBt.setName("epBackwardBt"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epBackwardBt, gridBagConstraints);

        epHAddressLabel.setText(resourceMap.getString("epHAddressLabel.text")); // NOI18N
        epHAddressLabel.setName("epHAddressLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        toolPanel.add(epHAddressLabel, gridBagConstraints);

        epVAddressLabel.setText(resourceMap.getString("epVAddressLabel.text")); // NOI18N
        epVAddressLabel.setName("epVAddressLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        toolPanel.add(epVAddressLabel, gridBagConstraints);

        epHSenderLabel.setText(resourceMap.getString("epHSenderLabel.text")); // NOI18N
        epHSenderLabel.setName("epHSenderLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        toolPanel.add(epHSenderLabel, gridBagConstraints);

        epVSenderLabel.setText(resourceMap.getString("epVSenderLabel.text")); // NOI18N
        epVSenderLabel.setName("epVSenderLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        toolPanel.add(epVSenderLabel, gridBagConstraints);

        epHGraphicLabel.setText(resourceMap.getString("epHGraphicLabel.text")); // NOI18N
        epHGraphicLabel.setName("epHGraphicLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        toolPanel.add(epHGraphicLabel, gridBagConstraints);

        epVGraphicLabel.setText(resourceMap.getString("epVGraphicLabel.text")); // NOI18N
        epVGraphicLabel.setName("epVGraphicLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        toolPanel.add(epVGraphicLabel, gridBagConstraints);

        epEnvAxisLabel.setText(resourceMap.getString("epEnvAxisLabel.text")); // NOI18N
        epEnvAxisLabel.setName("epEnvAxisLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        toolPanel.add(epEnvAxisLabel, gridBagConstraints);

        epEnvTypeLabel.setText(resourceMap.getString("epEnvTypeLabel.text")); // NOI18N
        epEnvTypeLabel.setName("epEnvTypeLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        toolPanel.add(epEnvTypeLabel, gridBagConstraints);

        epAddressFontPreviewTB.setText(resourceMap.getString("epAddressFontPreviewTB.text")); // NOI18N
        epAddressFontPreviewTB.setMinimumSize(new java.awt.Dimension(250, 20));
        epAddressFontPreviewTB.setName("epAddressFontPreviewTB"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epAddressFontPreviewTB, gridBagConstraints);

        epSenderFontPreviewTB.setText(resourceMap.getString("epSenderFontPreviewTB.text")); // NOI18N
        epSenderFontPreviewTB.setMinimumSize(new java.awt.Dimension(250, 20));
        epSenderFontPreviewTB.setName("epSenderFontPreviewTB"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epSenderFontPreviewTB, gridBagConstraints);

        epGraphicPathTB.setColumns(200);
        epGraphicPathTB.setText(resourceMap.getString("epGraphicPathTB.text")); // NOI18N
        epGraphicPathTB.setMinimumSize(new java.awt.Dimension(250, 20));
        epGraphicPathTB.setName("epGraphicPathTB"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epGraphicPathTB, gridBagConstraints);

        buttonGroup1.add(epSenderLocCornerRB);
        epSenderLocCornerRB.setText(resourceMap.getString("epSenderLocCornerRB.text")); // NOI18N
        epSenderLocCornerRB.setName("epSenderLocCornerRB"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        toolPanel.add(epSenderLocCornerRB, gridBagConstraints);

        buttonGroup1.add(epSenderLocLineRB);
        epSenderLocLineRB.setText(resourceMap.getString("epSenderLocLineRB.text")); // NOI18N
        epSenderLocLineRB.setName("epSenderLocLineRB"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        toolPanel.add(epSenderLocLineRB, gridBagConstraints);

        epCount.setMinimumSize(new java.awt.Dimension(50, 20));
        epCount.setName("epCount"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epCount, gridBagConstraints);

        epCountLabel.setText(resourceMap.getString("epCountLabel.text")); // NOI18N
        epCountLabel.setName("epCountLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolPanel.add(epCountLabel, gridBagConstraints);

        buttonGroup2.add(epOrderTable);
        epOrderTable.setText(resourceMap.getString("epOrderTable.text")); // NOI18N
        epOrderTable.setName("epOrderTable"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        toolPanel.add(epOrderTable, gridBagConstraints);

        buttonGroup2.add(epOrderTeam);
        epOrderTeam.setText(resourceMap.getString("epOrderTeam.text")); // NOI18N
        epOrderTeam.setName("epOrderTeam"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        toolPanel.add(epOrderTeam, gridBagConstraints);

        jScrollPane1.setViewportView(toolPanel);

        jSplitPane1.setBottomComponent(jScrollPane1);

        jScrollPane2.setName("jScrollPane2"); // NOI18N
        jScrollPane2.setViewportView(previewPanel);

        previewPanel.setMinimumSize(new java.awt.Dimension(1024, 500));
        previewPanel.setName("previewPanel"); // NOI18N

        javax.swing.GroupLayout previewPanelLayout = new javax.swing.GroupLayout(previewPanel);
        previewPanel.setLayout(previewPanelLayout);
        previewPanelLayout.setHorizontalGroup(
            previewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1099, Short.MAX_VALUE)
        );
        previewPanelLayout.setVerticalGroup(
            previewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(previewPanel);

        jSplitPane1.setLeftComponent(jScrollPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jSplitPane1, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jSeparator1.setName("jSeparator1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jSeparator1, gridBagConstraints);

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenu1.add(jMenuItem1);

        jSeparator2.setName("jSeparator2"); // NOI18N
        jMenu1.add(jSeparator2);

        jMenuItem2.setText(resourceMap.getString("jMenuItem2.text")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText(resourceMap.getString("jMenuItem3.text")); // NOI18N
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenu1.add(jMenuItem3);

        jSeparator3.setName("jSeparator3"); // NOI18N
        jMenu1.add(jSeparator3);

        jMenuItem4.setText(resourceMap.getString("jMenuItem4.text")); // NOI18N
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);
       
        setJMenuBar(jMenuBar1);
        setVisible(true);
        pack();
    }// </editor-fold>

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify
     public javax.swing.ButtonGroup buttonGroup1;
     public javax.swing.ButtonGroup buttonGroup2;
     public javax.swing.JCheckBox enSenderCheckBox;
     public javax.swing.JButton epAddressFontBt;
     public javax.swing.JTextField epAddressFontPreviewTB;
     public javax.swing.JButton epBackwardBt;
     public javax.swing.JSpinner epCount;
     public javax.swing.JLabel epCountLabel;
     public javax.swing.JButton epDeclineBt;
     public javax.swing.JLabel epEnvAxisLabel;
     public javax.swing.JLabel epEnvTypeLabel;
     public javax.swing.JComboBox epEnvelopeAxis;
     public javax.swing.JComboBox epEnvelopeType;
     public javax.swing.JButton epFowardBt;
     public javax.swing.JButton epGraphicBt;
     public javax.swing.JCheckBox epGraphicCheckBox;
     public javax.swing.JTextField epGraphicPathTB;
     public javax.swing.JLabel epHAddressLabel;
     public javax.swing.JSpinner epHAddressLoc;
     public javax.swing.JLabel epHGraphicLabel;
     public javax.swing.JSpinner epHGraphicLoc;
     public javax.swing.JLabel epHSenderLabel;
     public javax.swing.JSpinner epHSenderLoc;
     public javax.swing.JButton epHomeBt;
     public javax.swing.JRadioButton epOrderTable;
     public javax.swing.JRadioButton epOrderTeam;
     public javax.swing.JButton epPrintBt;
     public javax.swing.JButton epSenderFontBt;
     public javax.swing.JTextField epSenderFontPreviewTB;
     public javax.swing.JRadioButton epSenderLocCornerRB;
     public javax.swing.JRadioButton epSenderLocLineRB;
     public javax.swing.JLabel epVAddressLabel;
     public javax.swing.JSpinner epVAddressLoc;
     public javax.swing.JLabel epVGraphicLabel;
     public javax.swing.JSpinner epVGraphicLoc;
     public javax.swing.JLabel epVSenderLabel;
     public javax.swing.JSpinner epVSenderLoc;
     public javax.swing.JLabel jLabel1;
     public javax.swing.JMenu jMenu1;
     public javax.swing.JMenuBar jMenuBar1;
     public javax.swing.JMenuItem jMenuItem1;
     public javax.swing.JMenuItem jMenuItem2;
     public javax.swing.JMenuItem jMenuItem3;
     public javax.swing.JMenuItem jMenuItem4;
     public javax.swing.JScrollPane jScrollPane1;
     public javax.swing.JScrollPane jScrollPane2;
     public javax.swing.JSeparator jSeparator1;
     public javax.swing.JSeparator jSeparator2;
     public javax.swing.JSeparator jSeparator3;
     public javax.swing.JSplitPane jSplitPane1;
     public ExtendedJPanelImpl previewPanel;
     public ExtendedJPanelImpl toolPanel;
    // End of variables declaration

}
