package org.en.tealEye.printing.gui;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GenericFontFrame.java
 *
 * Created on 11.09.2009, 18:25:19
 */
import javax.swing.*;
import java.awt.*;
import java.util.ResourceBundle;



/**
 *
 * @author Stephan Pudras
 */
public class GenericFontFrame extends javax.swing.JFrame {

    /** Creates new form GenericFontFrame */
    public GenericFontFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        genericFontFrameHeaderLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        genericFontFrameTypeList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        genericFontFrameStyleList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        genericFontFrameSizeList = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        genericFontFramePreviewArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        genericFontFrameAcceptBt = new javax.swing.JButton();
        genericFontFrameDeclineBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        genericFontFrameHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResourceBundle resourceMap = ResourceBundle.getBundle("org.en.tealEye.resources.GenericFontFrame");
        genericFontFrameHeaderLabel.setText(resourceMap.getString("genericFontFrameHeaderLabel.text")); // NOI18N
        genericFontFrameHeaderLabel.setName("genericFontFrameHeaderLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(genericFontFrameHeaderLabel, gridBagConstraints);



        jScrollPane1.setName("jScrollPane1"); // NOI18N


        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] fonts = ge.getAvailableFontFamilyNames();
        DefaultListModel model = new DefaultListModel();
        int i = 0;
        for(String s: fonts) {
            model.add(i++,s);
        }
        genericFontFrameTypeList.setModel(model);
        genericFontFrameTypeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        genericFontFrameTypeList.setToolTipText(resourceMap.getString("genericFontFrameTypeList.toolTipText")); // NOI18N
        genericFontFrameTypeList.setName("genericFontFrameTypeList"); // NOI18N
        jScrollPane1.setViewportView(genericFontFrameTypeList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPane1, gridBagConstraints);


        jScrollPane2.setName("jScrollPane2"); // NOI18N
        genericFontFrameSizeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        genericFontFrameSizeList.setModel(new javax.swing.AbstractListModel() {
            int[] strings = { 6, 8, 10, 11, 12, 13, 14, 15, 16, 18, 20, 22, 24, 26, 28, 30  };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        genericFontFrameSizeList.setToolTipText(resourceMap.getString("genericFontFrameSizeList.toolTipText")); // NOI18N
        genericFontFrameSizeList.setName("genericFontFrameSizeList"); // NOI18N
        jScrollPane2.setViewportView(genericFontFrameSizeList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jScrollPane3.setMaximumSize(new java.awt.Dimension(130, 200));
        jScrollPane3.setName("jScrollPane3"); // NOI18N

        genericFontFrameStyleList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "normal","fett","kursiv","fett-kursiv" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        genericFontFrameStyleList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        genericFontFrameStyleList.setName("genericFontFrameStyleList");
        genericFontFrameStyleList.setToolTipText(resourceMap.getString("genericFontFrameStyleList.toolTipText")); // NOI18N
        jScrollPane3.setViewportView(genericFontFrameStyleList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPane3, gridBagConstraints);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        genericFontFramePreviewArea.setColumns(20);
        genericFontFramePreviewArea.setRows(5);
        genericFontFramePreviewArea.setName("genericFontFramePreviewArea"); // NOI18N
        jScrollPane4.setViewportView(genericFontFramePreviewArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPane4, gridBagConstraints);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        genericFontFrameAcceptBt.setText(resourceMap.getString("genericFontFrameAcceptBt.text")); // NOI18N
        genericFontFrameAcceptBt.setName("genericFontFrameAcceptBt"); // NOI18N
        jPanel1.add(genericFontFrameAcceptBt);

        genericFontFrameDeclineBt.setText(resourceMap.getString("genericFontFrameDeclineBt.text")); // NOI18N
        genericFontFrameDeclineBt.setName("genericFontFrameDeclineBt"); // NOI18N
        jPanel1.add(genericFontFrameDeclineBt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        genericFontFramePreviewArea.setText("The Quick Brown Fox Jumps Over The Lazy Dog!");

        pack();
        setVisible(true);
    }// </editor-fold>

    /**
    * @param args the command line arguments
    */

    

    // Variables declaration - do not modify
    private javax.swing.JButton genericFontFrameAcceptBt;
    private javax.swing.JButton genericFontFrameDeclineBt;
    private javax.swing.JLabel genericFontFrameHeaderLabel;
    private javax.swing.JTextArea genericFontFramePreviewArea;
    private javax.swing.JList genericFontFrameSizeList;
    private javax.swing.JList genericFontFrameStyleList;
    private javax.swing.JList genericFontFrameTypeList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration

}
