package org.en.tealEye.printing.gui;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SenderValueFrame.java
 *
 * Created on 12.09.2009, 14:06:33
 */


import java.util.ResourceBundle;

/**
 *
 * @author Stephan Pudras
 */
public class SenderAddressFrame extends javax.swing.JFrame {

    /** Creates new form SenderValueFrame */
    public SenderAddressFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        senderHeaderLabel = new javax.swing.JLabel();
        senderNameLabel = new javax.swing.JLabel();
        senderCorpLabel = new javax.swing.JLabel();
        senderPLZLabel = new javax.swing.JLabel();
        senderLocationLabel = new javax.swing.JLabel();
        senderStreetLabel = new javax.swing.JLabel();
        senderAddressFrameCorpTF = new javax.swing.JTextField();
        senderAddressFrameNameTF = new javax.swing.JTextField();
        senderAddressFramePLZTF = new javax.swing.JTextField();
        senderAddressFrameLocationTF = new javax.swing.JTextField();
        senderAddressFrameStreetTF = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        senderAddressFrameAcceptBt = new javax.swing.JButton();
        senderAddressFrameDeclineBt = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ResourceBundle resourceMap = ResourceBundle.getBundle("org.en.tealEye.resources.SenderAddressFrame");
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        senderHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        senderHeaderLabel.setText(resourceMap.getString("senderHeaderLabel.text")); // NOI18N
        senderHeaderLabel.setName("senderHeaderLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(senderHeaderLabel, gridBagConstraints);

        senderNameLabel.setText(resourceMap.getString("senderNameLabel.text")); // NOI18N
        senderNameLabel.setName("senderNameLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(senderNameLabel, gridBagConstraints);

        senderCorpLabel.setText(resourceMap.getString("senderCorpLabel.text")); // NOI18N
        senderCorpLabel.setName("senderCorpLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(senderCorpLabel, gridBagConstraints);

        senderPLZLabel.setText(resourceMap.getString("senderPLZLabel.text")); // NOI18N
        senderPLZLabel.setName("senderPLZLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(senderPLZLabel, gridBagConstraints);

        senderLocationLabel.setText(resourceMap.getString("senderLocationLabel.text")); // NOI18N
        senderLocationLabel.setName("senderLocationLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(senderLocationLabel, gridBagConstraints);

        senderStreetLabel.setText(resourceMap.getString("senderStreetLabel.text")); // NOI18N
        senderStreetLabel.setName("senderStreetLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(senderStreetLabel, gridBagConstraints);

        senderAddressFrameCorpTF.setText(resourceMap.getString("senderAddressFrameCorpTF.text")); // NOI18N
        senderAddressFrameCorpTF.setName("senderAddressFrameCorpTF"); // NOI18N
        senderAddressFrameCorpTF.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(senderAddressFrameCorpTF, gridBagConstraints);

        senderAddressFrameNameTF.setText(resourceMap.getString("senderAddressFrameNameTF.text")); // NOI18N
        senderAddressFrameNameTF.setName("senderAddressFrameNameTF"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(senderAddressFrameNameTF, gridBagConstraints);

        senderAddressFramePLZTF.setText(resourceMap.getString("senderAddressFramePLZTF.text")); // NOI18N
        senderAddressFramePLZTF.setMinimumSize(new java.awt.Dimension(50, 20));
        senderAddressFramePLZTF.setName("senderAddressFramePLZTF"); // NOI18N
        senderAddressFramePLZTF.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(senderAddressFramePLZTF, gridBagConstraints);

        senderAddressFrameLocationTF.setText(resourceMap.getString("senderAddressFrameLocationTF.text")); // NOI18N
        senderAddressFrameLocationTF.setName("senderAddressFrameLocationTF"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(senderAddressFrameLocationTF, gridBagConstraints);

        senderAddressFrameStreetTF.setText(resourceMap.getString("senderAddressFrameStreetTF.text")); // NOI18N
        senderAddressFrameStreetTF.setName("senderAddressFrameStreetTF"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(senderAddressFrameStreetTF, gridBagConstraints);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 20));

        senderAddressFrameAcceptBt.setText(resourceMap.getString("senderAddressFrameAcceptBt.text")); // NOI18N
        senderAddressFrameAcceptBt.setName("senderAddressFrameAcceptBt"); // NOI18N
        jPanel1.add(senderAddressFrameAcceptBt);

        senderAddressFrameDeclineBt.setText(resourceMap.getString("senderAddressFrameDeclineBt.text")); // NOI18N
        senderAddressFrameDeclineBt.setName("senderAddressFrameDeclineBt"); // NOI18N
        jPanel1.add(senderAddressFrameDeclineBt);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        getContentPane().add(jPanel1, gridBagConstraints);

        jSeparator1.setName("jSeparator1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 5, 5);
        getContentPane().add(jSeparator1, gridBagConstraints);

        pack();
        setVisible(true);
    }// </editor-fold>

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton senderAddressFrameAcceptBt;
    private javax.swing.JTextField senderAddressFrameCorpTF;
    private javax.swing.JButton senderAddressFrameDeclineBt;
    private javax.swing.JTextField senderAddressFrameLocationTF;
    private javax.swing.JTextField senderAddressFrameNameTF;
    private javax.swing.JTextField senderAddressFramePLZTF;
    private javax.swing.JTextField senderAddressFrameStreetTF;
    private javax.swing.JLabel senderCorpLabel;
    private javax.swing.JLabel senderHeaderLabel;
    private javax.swing.JLabel senderLocationLabel;
    private javax.swing.JLabel senderNameLabel;
    private javax.swing.JLabel senderPLZLabel;
    private javax.swing.JLabel senderStreetLabel;
    // End of variables declaration

}
