package org.en.tealEye.guiPanels.applicationLogicPanels;

import de.liga.dart.ligateam.model.TeamWunsch;
import de.liga.dart.model.Ligateam;
import de.liga.dart.model.Spielort;
import de.liga.util.CalendarUtils;
import de.liga.util.StringUtils;
import org.en.tealEye.framework.BeanTableModel;
import org.en.tealEye.guiExt.ExtPanel.ExtJEditPanel;
import org.en.tealEye.guiExt.ExtPanel.JExtTextField;
import org.en.tealEye.guiMain.DartComponentRegistry;
import org.en.tealEye.guiMain.util.LigaSelectable;
import org.en.tealEye.guiMain.util.LigaklasseSelectable;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.*;

/** @author Stephan */
public class CreateTeam extends ExtJEditPanel
      implements LigaSelectable, LigaklasseSelectable, ActionListener, FocusListener {
    private JButton teamNew;
    private JButton teamInfo;
    private JComboBox teamWunschListSortCombo;
    private JLabel filterLigaclassLabel;

    /** Creates new form CreateTeam */
    public CreateTeam() {
        setName("CreateTeam");
        setTitle("Team bearbeiten");

        initComponents();

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Erzeugter Quelltext ">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        formularPanel = new javax.swing.JPanel();
        textfieldPanel = new javax.swing.JPanel();
        teamName = new javax.swing.JTextField();
        teamLocation = new JExtTextField();
        teamLocation.setProperty("spielortName");
        teamDay = new javax.swing.JComboBox();
        teamLeague = new javax.swing.JComboBox();
        teamTime = new JTextField();
        teamNameLabel = new javax.swing.JLabel();
        teamLocationLabel = new javax.swing.JLabel();
        teamDayLabel = new javax.swing.JLabel();
        teamTimeLabel = new javax.swing.JLabel();
        teamLeagueLabel = new javax.swing.JLabel();
        teamLeagueClass = new javax.swing.JComboBox();
        teamLeagueClassLabel = new javax.swing.JLabel();
        teamLeagueGroupLabel = new javax.swing.JLabel();
        listPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teamWunschListTarget = new javax.swing.JList();
        teamWunschListTarget.setName("List_TeamWunschList");
        jScrollPane2 = new javax.swing.JScrollPane();
        possibleTeamsForWunschList = new javax.swing.JList();
        teamWunschListAdd = new javax.swing.JButton();
        teamWunschListRemove = new javax.swing.JButton();
        teamWunschListLeagueClass = new javax.swing.JComboBox();
        teamWunschListPoolLabel = new javax.swing.JLabel();
        teamWunschListTargetLabel = new javax.swing.JLabel();
        teamWunschListSortCombo = new JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        tablePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        teamLocationTable = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        buttonNestedPanel = new javax.swing.JPanel();
        teamAccept = new javax.swing.JButton();
        teamDecline = new javax.swing.JButton();

        teamNew = new JButton();
        setLayout(new java.awt.GridBagLayout());
        teamInfo = new JButton();

        teamTime.addFocusListener(this);

        headerPanel.setLayout(new java.awt.GridBagLayout());

        headerPanel.setBorder(new javax.swing.border.LineBorder(
              new java.awt.Color(153, 153, 153), 1, true));
        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 18));
        headerLabel.setText(getTitle());
        headerPanel.add(headerLabel, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 5, 3);
        add(headerPanel, gridBagConstraints);

        formularPanel.setLayout(new java.awt.GridBagLayout());

        formularPanel.setBorder(new javax.swing.border.LineBorder(
              new java.awt.Color(153, 153, 153), 1, true));
        textfieldPanel.setLayout(new java.awt.GridBagLayout());

        textfieldPanel.setBorder(new javax.swing.border.LineBorder(
              new java.awt.Color(204, 204, 204), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        textfieldPanel.add(teamName, gridBagConstraints);

        teamLocation.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        textfieldPanel.add(teamLocation, gridBagConstraints);

        teamDay.setModel(new DefaultComboBoxModel(new String[]{"Montag", "Dienstag",
              "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"}));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        textfieldPanel.add(teamDay, gridBagConstraints);

        teamLeague.setName("Combo_Liga");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        textfieldPanel.add(teamLeague, gridBagConstraints);

        teamTime.setMinimumSize(new java.awt.Dimension(60, 20));
        teamTime.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        textfieldPanel.add(teamTime, gridBagConstraints);

        teamNameLabel.setText("Teamname");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        textfieldPanel.add(teamNameLabel, gridBagConstraints);

        teamLocationLabel.setText("Spielort");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        textfieldPanel.add(teamLocationLabel, gridBagConstraints);

        teamDayLabel.setText("Spieltag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        textfieldPanel.add(teamDayLabel, gridBagConstraints);

        teamTimeLabel.setText("Spielzeit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        textfieldPanel.add(teamTimeLabel, gridBagConstraints);

        teamLeagueLabel.setText("Liga");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        textfieldPanel.add(teamLeagueLabel, gridBagConstraints);

        teamLeagueClass.setName("Combo_Ligaklasse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        textfieldPanel.add(teamLeagueClass, gridBagConstraints);

        teamLeagueClassLabel.setText("Ligaklasse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        textfieldPanel.add(teamLeagueClassLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        textfieldPanel.add(teamLeagueGroupLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        formularPanel.add(textfieldPanel, gridBagConstraints);

        listPanel.setLayout(new java.awt.GridBagLayout());

        listPanel.setBorder(new javax.swing.border.LineBorder(
              new java.awt.Color(204, 204, 204), 1, true));
        jScrollPane1.setViewportView(teamWunschListTarget);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        listPanel.add(jScrollPane1, gridBagConstraints);

        possibleTeamsForWunschList.setName("List_possibleTeamsForWunschList");
        jScrollPane2.setViewportView(possibleTeamsForWunschList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        listPanel.add(jScrollPane2, gridBagConstraints);

        teamWunschListAdd.setText("Hinzuf\u00fcgen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 0.2;
        //listPanel.add(teamWunschListAdd, gridBagConstraints);

        teamWunschListRemove.setText("Entfernen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        //listPanel.add(teamWunschListRemove, gridBagConstraints);

        teamWunschListLeagueClass.setName("Combo_WunschListLigaklasse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 5);
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        listPanel.add(teamWunschListLeagueClass, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 5);
        filterLigaclassLabel = new JLabel("Ligaklasse");
        listPanel.add(filterLigaclassLabel, gridBagConstraints);

        teamWunschListSortCombo.setName("Combo_WunschArten");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 5);
        listPanel.add(teamWunschListSortCombo, gridBagConstraints);

        teamWunschListPoolLabel.setText("W\u00e4hlbare Teams");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        listPanel.add(teamWunschListPoolLabel, gridBagConstraints);

        teamWunschListTargetLabel.setText("Sonderwünsche");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        listPanel.add(teamWunschListTargetLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        listPanel.add(jSeparator1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        formularPanel.add(listPanel, gridBagConstraints);

        tablePanel.setLayout(new java.awt.GridBagLayout());

        tablePanel.setBorder(new javax.swing.border.LineBorder(
              new java.awt.Color(204, 204, 204), 1, true));
        teamLocationTable.setName("Table_SpielortProLiga");
        jScrollPane3.setViewportView(teamLocationTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        tablePanel.add(jScrollPane3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        formularPanel.add(tablePanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(formularPanel, gridBagConstraints);

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        buttonPanel.setBorder(new javax.swing.border.LineBorder(
              new java.awt.Color(153, 153, 153), 1, true));
        buttonNestedPanel.setLayout(new java.awt.GridBagLayout());

        teamAccept.setText("Speichern");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 5, 3);
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        buttonNestedPanel.add(teamAccept, gridBagConstraints);

        teamDecline.setText("Abbrechen");

        teamDecline.setToolTipText("Dieses Fenster schliessen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 5, 3);
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        buttonNestedPanel.add(teamDecline, gridBagConstraints);

        teamNew.setText("Neue Daten");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 5, 3);
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        buttonNestedPanel.add(teamNew, gridBagConstraints);

        teamInfo.setText("Infos...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 5, 3);
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        buttonNestedPanel.add(teamInfo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        buttonPanel.add(buttonNestedPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formularPanel.add(buttonPanel, gridBagConstraints);

        teamNew.setName("neu");
        teamNew.setMnemonic(KeyEvent.VK_N);
        teamAccept.setName("speichern");
        teamAccept.setMnemonic(KeyEvent.VK_S);
        teamDecline.setName("abbrechen");
        teamDecline.setMnemonic(KeyEvent.VK_A);
        teamInfo.setName("infos");
        teamInfo.setMnemonic(KeyEvent.VK_I);

        getWunschListTeams().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                TeamWunsch wunsch = (TeamWunsch) teamWunschListTarget.getSelectedValue();
                if (wunsch != null) {
                    teamWunschListSortCombo.setSelectedItem(wunsch.getWunschArtName());
                }
            }
        });
    }// </editor-fold>

    protected void doUpdatePanel() {
        if (getModelEntity() != null) {
            Ligateam team = (Ligateam) getModelEntity();
            DartComponentRegistry.getInstance()
                    .setComboBoxModel(getLiga(), this); // zum Setzen der Selection!
//            System.out.println("[" + Thread.currentThread().getName() + "] " + "SETZTE AUF " + team.getLiga());
            teamLeague.setSelectedItem(team.getLiga());
        }

        super.doUpdatePanel();    // call super!
        if (getModelEntity() == null) {
            teamLeagueGroupLabel.setText("");
        } else {
            Ligateam team = (Ligateam) getModelEntity();
            if (team.getLigateamspiel() != null) {
                getLigaklasse().setEnabled(false);
                getLiga().setEnabled(false);
                teamLeagueGroupLabel.setText(" Spielt in Gruppe " + team
                      .getLigateamspiel().getLigagruppe().getGruppenName() +
                      " auf Platz " + team.getLigateamspiel().getPlatzNr() + ".");
            } else {
                getLigaklasse().setEnabled(true);
                getLiga().setEnabled(true);
                teamLeagueGroupLabel.setText(" Noch in keiner Gruppe eingeteilt!");
            }
        }
    }

    public void clearTextAreas() {
        super.clearTextAreas();    // call super!
        getLigaklasse().setEnabled(true);
        getLiga().setEnabled(true);
        getSpielzeit().setText("19:30");
        teamLeagueGroupLabel.setText("");
        getWochentagName().setSelectedItem(CalendarUtils.getWeekdayName(7));
        DartComponentRegistry.getInstance()
              .setListModel(teamWunschListTarget, this);
        DartComponentRegistry.getInstance()
              .setListModel(possibleTeamsForWunschList, this);
        getTeamName().requestFocus();
    }

    /// / Variablendeklaration - nicht modifizieren
    private javax.swing.JPanel buttonNestedPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel formularPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton teamAccept;
    private javax.swing.JButton teamWunschListAdd;
    private javax.swing.JComboBox teamWunschListLeagueClass;
    private javax.swing.JList possibleTeamsForWunschList;
    private javax.swing.JLabel teamWunschListPoolLabel;
    private javax.swing.JButton teamWunschListRemove;
    private javax.swing.JList teamWunschListTarget;
    private javax.swing.JLabel teamWunschListTargetLabel;
    private javax.swing.JComboBox teamDay;
    private javax.swing.JLabel teamDayLabel;
    private javax.swing.JButton teamDecline;
    private javax.swing.JComboBox teamLeague;
    private javax.swing.JComboBox teamLeagueClass;
    private javax.swing.JLabel teamLeagueClassLabel;
    private javax.swing.JLabel teamLeagueGroupLabel;
    private javax.swing.JLabel teamLeagueLabel;
    private JExtTextField teamLocation;
    private javax.swing.JLabel teamLocationLabel;
    private javax.swing.JTable teamLocationTable;
    private javax.swing.JTextField teamName;
    private javax.swing.JLabel teamNameLabel;
    private javax.swing.JTextField teamTime;
    private javax.swing.JLabel teamTimeLabel;
    private javax.swing.JPanel textfieldPanel;
    // Ende der Variablendeklaration

    public JTextField getSpielzeit() {
        return teamTime;
    }

    public JTextField getTeamName() {
        return teamName;
    }

    public JList getPossibleTeamsForWunschList() {
        return possibleTeamsForWunschList;
    }

    public JComboBox getLigaklasse() {
        return teamLeagueClass;
    }

    public JComboBox getWunschListLigaklasse() {
        return teamWunschListLeagueClass;
    }

    public JComboBox getLiga() {
        return teamLeague;
    }

    public JComboBox getWochentagName() {
        return teamDay;
    }

    public JList getWunschListTeams() {
        return teamWunschListTarget;
    }

    public JTable getJTable1() {
        return teamLocationTable;
    }

    public void actionPerformed(ActionEvent e) {
        Object obj = e.getSource();
        if (obj instanceof JButton) {
            JButton button = (JButton) obj;
            if (button.equals(teamAccept)) {
                teamNew.setEnabled(true);
            } else if (button.equals(teamDecline)) {
            } else if (button.equals(teamNew)) {
                clearTextAreas();
                teamNew.setEnabled(false);
            }
        }
    }

    public Class getModelClass() {
        return Ligateam.class;
    }


    public JExtTextField getSpielort() {
        return teamLocation;

    }


    public Spielort getSelectedTableObject() {
        return (Spielort) ((BeanTableModel) teamLocationTable.getModel())
              .getObject(teamLocationTable.getSelectedRow());
    }


    public void setSpielortTextField() {
        teamLocation.setObject(getSelectedTableObject());
    }

    public void focusGained(FocusEvent e) {
        // do nothing
    }

    public void focusLost(FocusEvent e) {
        Object obj = e.getSource();
        if (obj.equals(teamTime)) {
            teamTime.setText(StringUtils.fixTimeString(teamTime.getText()));
        }
    }


    public void setTextfieldFocus() {
        teamName.requestFocus();
    }
}
