package org.en.tealEye.guiPanels.applicationLogicPanels;

import de.liga.dart.model.Ligagruppe;
import org.en.tealEye.guiExt.ExtPanel.ShowTablePanel;
import org.en.tealEye.guiMain.util.LigaSelectable;
import org.en.tealEye.guiMain.util.SpielortSelectable;

import javax.swing.*;

/**
 * @author Stephan
 */
public class ShowGroups extends ShowTablePanel implements LigaSelectable, SpielortSelectable {

    /**
     * Creates new form ShowGroups
     */
    public ShowGroups() {
        setName("ShowGroups");
        setTitle("Gruppen anzeigen");

        initComponents();
    }

    public Class getModelClass() {
        return Ligagruppe.class;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Erzeugter Quelltext ">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        comboPanel = new javax.swing.JPanel();
        showGroupsLeague = new javax.swing.JComboBox();
        showGroupsLeague.setName("Combo_LigaMitLeer");
        showGroupsLocation = new javax.swing.JComboBox();
        showGroupsLeagueLabel = new javax.swing.JLabel();
        showGroupsLocationLabel = new javax.swing.JLabel();

        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.setName("Table_Ligagruppe");
        showGroupsLocation.setName("Combo_SpielortMitLeer");

        setLayout(new java.awt.GridBagLayout());

        headerPanel.setLayout(new java.awt.GridBagLayout());

        headerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText(getTitle());
        headerPanel.add(jLabel1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        add(headerPanel, gridBagConstraints);

        formPanel.setLayout(new java.awt.GridBagLayout());

        formPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        comboPanel.setLayout(new java.awt.GridBagLayout());

        comboPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 10);
        comboPanel.add(showGroupsLeague, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 10);
        comboPanel.add(showGroupsLocation, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        comboPanel.add(getBtShowGroupsDelete(), gridBagConstraints);

        showGroupsLeagueLabel.setText("Liga");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        comboPanel.add(showGroupsLeagueLabel, gridBagConstraints);

        showGroupsLocationLabel.setText("Spielort");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        comboPanel.add(showGroupsLocationLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        comboPanel.add(getBtShowGroupsSort(), gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 10);
        comboPanel.add(getToggleDelete(), gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        formPanel.add(comboPanel, gridBagConstraints);

        tablePanel.setLayout(new java.awt.GridBagLayout());

        tablePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        tablePanel.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        formPanel.add(tablePanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(formPanel, gridBagConstraints);
    }// </editor-fold>


    // Variablendeklaration - nicht modifizieren
    private javax.swing.JPanel comboPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox showGroupsLeague;
    private javax.swing.JLabel showGroupsLeagueLabel;
    private javax.swing.JComboBox showGroupsLocation;
    private javax.swing.JLabel showGroupsLocationLabel;
    private javax.swing.JPanel tablePanel;
    // Ende der Variablendeklaration


    public JComboBox getLiga() {
        return showGroupsLeague;
    }

    public JComboBox getSpielort() {
        return showGroupsLocation;
    }

    public void setShowGroupsLocation(JComboBox showGroupsLocation) {
        this.showGroupsLocation = showGroupsLocation;
    }

    public JTable getLigagruppe() {
        return jTable1;
    }

    public void setJTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

}
