package org.en.tealEye.guiPanels.applicationLogicPanels;

import de.liga.dart.model.Automatenaufsteller;
import org.en.tealEye.framework.SwingUtils;
import org.en.tealEye.guiExt.ExtPanel.ExtJEditPanel;
import org.en.tealEye.guiMain.util.LigaSelectable;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;

/**
 * @author Stephan
 */
public class CreateVendor extends ExtJEditPanel implements LigaSelectable, ActionListener {

    private JButton vendorNew;

    /**
     * Creates new form CreateVendor
     */
    public CreateVendor() {
        setName("CreateVendor");
        setTitle("Aufsteller bearbeiten");

        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Erzeugter Quelltext ">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        formularPanel = new javax.swing.JPanel();
        vendorName = new javax.swing.JTextField();
        vendorStreet = new javax.swing.JTextField();
        vendorZip = new javax.swing.JTextField();
        SwingUtils.acceptDigitsOnly(vendorZip);
        vendorCity = new javax.swing.JTextField();
        vendorClerk = new javax.swing.JTextField();
        vendorPhone = new javax.swing.JTextField();
        vendorMobile = new javax.swing.JTextField();
        vendorFax = new javax.swing.JTextField();
        vendorEmail = new javax.swing.JTextField();
        vendorLeague = new javax.swing.JComboBox();
        vendorNameLabel = new javax.swing.JLabel();
        vendorStreetLabel = new javax.swing.JLabel();
        vendorZipLabel = new javax.swing.JLabel();
        vendorCityLabel = new javax.swing.JLabel();
        vendorClerkLabel = new javax.swing.JLabel();
        vendorPhoneLabel = new javax.swing.JLabel();
        vendorMobileLabel = new javax.swing.JLabel();
        vendorFaxLabel = new javax.swing.JLabel();
        vendorEmailLabel = new javax.swing.JLabel();
        vendorLeagueLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        buttonNestedPanel = new javax.swing.JPanel();
        vendorAccept = new javax.swing.JButton();
        vendorDecline = new javax.swing.JButton();
        vendorNew = new JButton("Neue Daten");
        vendorNew.setMnemonic(KeyEvent.VK_N);
        setLayout(new java.awt.GridBagLayout());
        vendorLeague.setName("Combo_LigaMitKeine");

        headerPanel.setLayout(new java.awt.GridBagLayout());

        headerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 18));
        headerLabel.setText(getTitle());
        headerPanel.add(headerLabel, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        add(headerPanel, gridBagConstraints);

        formularPanel.setLayout(new java.awt.GridBagLayout());

        formularPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        formularPanel.add(vendorName, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        formularPanel.add(vendorStreet, gridBagConstraints);

        vendorZip.setMinimumSize(new java.awt.Dimension(30, 20));
        vendorZip.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        formularPanel.add(vendorZip, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        formularPanel.add(vendorCity, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        formularPanel.add(vendorClerk, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        formularPanel.add(vendorPhone, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        formularPanel.add(vendorMobile, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        formularPanel.add(vendorFax, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        formularPanel.add(vendorEmail, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        formularPanel.add(vendorLeague, gridBagConstraints);

        vendorNameLabel.setText("Name der Firma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        formularPanel.add(vendorNameLabel, gridBagConstraints);

        vendorStreetLabel.setText("Strasse / Hausnummer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        formularPanel.add(vendorStreetLabel, gridBagConstraints);

        vendorZipLabel.setText("Postleitzahl");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        formularPanel.add(vendorZipLabel, gridBagConstraints);

        vendorCityLabel.setText("Ort");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        formularPanel.add(vendorCityLabel, gridBagConstraints);

        vendorClerkLabel.setText("Ansprechpartner");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        formularPanel.add(vendorClerkLabel, gridBagConstraints);

        vendorPhoneLabel.setText("Telefon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        formularPanel.add(vendorPhoneLabel, gridBagConstraints);

        vendorMobileLabel.setText("Mobil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        formularPanel.add(vendorMobileLabel, gridBagConstraints);

        vendorFaxLabel.setText("Fax");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        formularPanel.add(vendorFaxLabel, gridBagConstraints);

        vendorEmailLabel.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        formularPanel.add(vendorEmailLabel, gridBagConstraints);

        vendorLeagueLabel.setText("Liga");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        formularPanel.add(vendorLeagueLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(formularPanel, gridBagConstraints);

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        buttonPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        buttonNestedPanel.setLayout(new java.awt.GridBagLayout());

        vendorAccept.setText("Speichern");
        vendorAccept.setMnemonic(KeyEvent.VK_S);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        buttonNestedPanel.add(vendorAccept, gridBagConstraints);

        vendorDecline.setText("Abbrechen");
        vendorDecline.setMnemonic(KeyEvent.VK_A);
        vendorDecline.setToolTipText("Dieses Fenster schliessen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        buttonNestedPanel.add(vendorDecline, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        buttonPanel.add(buttonNestedPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 30);
        buttonNestedPanel.add(vendorNew, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(buttonPanel, gridBagConstraints);

        vendorNew.setName("neu");
        vendorAccept.setName("speichern");
        vendorDecline.setName("abbrechen");
    }// </editor-fold>

    // Variablendeklaration - nicht modifizieren
    private javax.swing.JPanel buttonNestedPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel formularPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton vendorAccept;
    private javax.swing.JTextField vendorCity;
    private javax.swing.JLabel vendorCityLabel;
    private javax.swing.JTextField vendorClerk;
    private javax.swing.JLabel vendorClerkLabel;
    private javax.swing.JButton vendorDecline;
    private javax.swing.JTextField vendorEmail;
    private javax.swing.JLabel vendorEmailLabel;
    private javax.swing.JTextField vendorFax;
    private javax.swing.JLabel vendorFaxLabel;
    private javax.swing.JComboBox vendorLeague;
    private javax.swing.JLabel vendorLeagueLabel;
    private javax.swing.JTextField vendorMobile;
    private javax.swing.JLabel vendorMobileLabel;
    private javax.swing.JTextField vendorName;
    private javax.swing.JLabel vendorNameLabel;
    private javax.swing.JTextField vendorPhone;
    private javax.swing.JLabel vendorPhoneLabel;
    private javax.swing.JTextField vendorStreet;
    private javax.swing.JLabel vendorStreetLabel;
    private javax.swing.JTextField vendorZip;
    private javax.swing.JLabel vendorZipLabel;
    // Ende der Variablendeklaration

    public JTextField getOrt() {
        return vendorCity;
    }

    public void setVendorCity(JTextField vendorCity) {
        this.vendorCity = vendorCity;
    }

    public JTextField getKontaktName() {
        return vendorClerk;
    }

    public void setVendorClerk(JTextField vendorClerk) {
        this.vendorClerk = vendorClerk;
    }

    public JTextField getEmail() {
        return vendorEmail;
    }

    public void setVendorEmail(JTextField vendorEmail) {
        this.vendorEmail = vendorEmail;
    }

    public JTextField getFax() {
        return vendorFax;
    }

    public void setVendorFax(JTextField vendorFax) {
        this.vendorFax = vendorFax;
    }

    public JComboBox getLiga() {
        return vendorLeague;
    }

    public void setVendorLeague(JComboBox vendorLeague) {
        this.vendorLeague = vendorLeague;
    }

    public JTextField getMobil() {
        return vendorMobile;
    }

    public void setVendorMobile(JTextField vendorMobile) {
        this.vendorMobile = vendorMobile;
    }

    public JTextField getAufstellerName() {
        return vendorName;
    }

    public void setVendorName(JTextField vendorName) {
        this.vendorName = vendorName;
    }

    public JTextField getTelefon() {
        return vendorPhone;
    }

    public void setVendorPhone(JTextField vendorPhone) {
        this.vendorPhone = vendorPhone;
    }

    public JTextField getStrasse() {
        return vendorStreet;
    }

    public void setVendorStreet(JTextField vendorStreet) {
        this.vendorStreet = vendorStreet;
    }

    public JTextField getPlz() {
        return vendorZip;
    }

    public void setVendorZip(JTextField vendorZip) {
        this.vendorZip = vendorZip;
    }

    public void actionPerformed(ActionEvent e) {
        Object obj = e.getSource();
        if (obj instanceof JButton) {
            JButton button = (JButton) obj;
            if (button.equals(vendorAccept)) {
                vendorNew.setEnabled(true);
            } else if (button.equals(vendorDecline)) {
            } else if (button.equals(vendorNew)) {
                clearTextAreas();
                vendorNew.setEnabled(false);
            }
        }
    }

    public Class getModelClass() {
        return Automatenaufsteller.class;
    }

    @Override
    public void clearTextAreas() {
        super.clearTextAreas();    // call super!
        getAufstellerName().requestFocus();
    }
}
