/*
 * PrintingDialog.java
 *
 * Created on 16. November 2007, 17:43
 */

package org.en.tealEye.printing.gui;

import org.en.tealEye.printing.controller.PrintingController;

import javax.swing.*;
import java.awt.*;

/**
 * @author Stephan
 */
public class PrintingDialogFrame extends javax.swing.JFrame {
    private JButton druckenButton;
    private JButton abbrechenButton;

    /**
     * Creates new form PrintingDialog
     */
    public PrintingDialogFrame(PrintingController pcontrol) {
        initComponents(pcontrol);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *
     * @param pcontrol
     */
    // <editor-fold defaultstate="collapsed" desc=" Erzeugter Quelltext ">
    private void initComponents(PrintingController pcontrol) {
        setTitle("Druckoptionen");
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        etikettenRadio = new javax.swing.JRadioButton();
        auswahlRadio = new javax.swing.JRadioButton();
        gruppenRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        alleRadio = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        druckenButton = new JButton("Drucken");
        abbrechenButton = new JButton("Abbrechen");
        envelopeRadio = new JRadioButton();
        getContentPane().setLayout(new java.awt.GridBagLayout());
        setPreferredSize(new Dimension(250, 250));
        this.setLocation(250, 250);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(auswahlRadio);
        etikettenRadio.setText("Etiketten drucken");
        etikettenRadio.setMnemonic('E');
        etikettenRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        etikettenRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(etikettenRadio, gridBagConstraints);
        buttonGroup1.add(envelopeRadio);

        envelopeRadio.setText("Briefumschläge beschriften");
        envelopeRadio.setMnemonic('B');
        envelopeRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        envelopeRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(envelopeRadio, gridBagConstraints);

        buttonGroup1.add(gruppenRadio);
        auswahlRadio.setText("Auswahl drucken");
        auswahlRadio.setMnemonic('w');
        auswahlRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        auswahlRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(auswahlRadio, gridBagConstraints);

        buttonGroup1.add(etikettenRadio);
        gruppenRadio.setText("Gruppentabellen drucken");
        gruppenRadio.setMnemonic('G');
        gruppenRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        gruppenRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(gruppenRadio, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Druckoptionen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel1, gridBagConstraints);

        buttonGroup1.add(alleRadio);
        alleRadio.setText("Alles drucken");
        alleRadio.setMnemonic('A');
        alleRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        alleRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(alleRadio, gridBagConstraints);


        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 2, 10);
        getContentPane().add(druckenButton, gridBagConstraints);


        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 2, 10);
        getContentPane().add(abbrechenButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jSeparator1, gridBagConstraints);

        druckenButton.addActionListener(pcontrol);
        abbrechenButton.addActionListener(pcontrol);

        setVisible(true);
        pack();
    }// </editor-fold>


    // Variablendeklaration - nicht modifizieren
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton auswahlRadio;
    private javax.swing.JRadioButton gruppenRadio;
    private javax.swing.JRadioButton etikettenRadio;
    private javax.swing.JRadioButton alleRadio;
    private JRadioButton envelopeRadio;
    private javax.swing.JSeparator jSeparator1;
    // Ende der Variablendeklaration

    public String getSelectedRadioBox() {
        if (auswahlRadio.isSelected()) return "auswahl";
        else if (gruppenRadio.isSelected()) return "gruppen";
        else if (etikettenRadio.isSelected()) return "etikett";
        else if (alleRadio.isSelected()) return "alle";
        else if (envelopeRadio.isSelected()) return "envelope";
        else return null;
    }

}
