/*
 * FontConfigPanel.java
 *
 * Created on 5. November 2007, 19:15
 */

package org.en.tealEye.guiPanels.ConfigPanels;

import org.en.tealEye.guiExt.ExtPanel.ExtendedJPanelImpl;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;

/**
 * @author Stephan
 */
public class FontConfigPanel extends ExtendedJPanelImpl implements ActionListener {

    private Font newFont;
    private Map<String, Font> editableFontMap = new HashMap<String, Font>();

    /**
     * Creates new form FontConfigPanel
     */
    public FontConfigPanel(ActionListener al) {

        initComponents(al);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Erzeugter Quelltext ">
    private void initComponents(ActionListener al) {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        labelFontPanel = new javax.swing.JPanel();
        labelFontType = new javax.swing.JComboBox();
        labelFontStyle = new javax.swing.JComboBox();
        labelFontSize = new javax.swing.JComboBox();
        formFontPanel = new javax.swing.JPanel();
        formFontType = new javax.swing.JComboBox();
        formFontStyle = new javax.swing.JComboBox();
        formFontSize = new javax.swing.JComboBox();
        tableFontPanel = new javax.swing.JPanel();
        tableFontType = new javax.swing.JComboBox();
        tableFontStyle = new javax.swing.JComboBox();
        tableFontSize = new javax.swing.JComboBox();
        previewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        buttonNestedPanel = new javax.swing.JPanel();
        fontConfigAccept = new javax.swing.JButton();
        fontConfigDecline = new javax.swing.JButton();

//edit
        labelFontType.addActionListener(this);
        labelFontStyle.addActionListener(this);
        labelFontSize.addActionListener(this);
        formFontType.addActionListener(this);
        formFontStyle.addActionListener(this);
        formFontSize.addActionListener(this);
        tableFontType.addActionListener(this);
        tableFontStyle.addActionListener(this);
        tableFontSize.addActionListener(this);

        fontConfigAccept.addActionListener(al);
        fontConfigDecline.addActionListener(al);

        fontConfigAccept.setActionCommand("BT_Font_Accept");
        fontConfigDecline.setActionCommand("BT_Font_Decline");

        labelFontType.setName("labelFontType");
        labelFontStyle.setName("labelFontStyle");
        labelFontSize.setName("labelFontSize");
        formFontType.setName("formFontType");
        formFontStyle.setName("formFontStyle");
        formFontSize.setName("formFontSize");
        tableFontType.setName("tableFontType");
        tableFontStyle.setName("tableFontStyle");
        tableFontSize.setName("tableFontSize");


        setLayout(new java.awt.GridBagLayout());

        headerPanel.setLayout(new java.awt.GridBagLayout());

        headerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Schriftarten einstellen");
        headerPanel.add(jLabel1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(headerPanel, gridBagConstraints);

        formPanel.setLayout(new java.awt.GridBagLayout());

        formPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        labelFontPanel.setLayout(new java.awt.GridBagLayout());

        labelFontPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Beschriftungen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
        labelFontType.setModel(new javax.swing.DefaultComboBoxModel(getAvailableFonts()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        labelFontPanel.add(labelFontType, gridBagConstraints);

        labelFontStyle.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"normal", "fett", "kursiv", "fett/kursiv"}));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        labelFontPanel.add(labelFontStyle, gridBagConstraints);

        labelFontSize.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"8", "9", "10", "11", "12", "13", "14", "16", "18", "20", "22", "24"}));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        labelFontPanel.add(labelFontSize, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        formPanel.add(labelFontPanel, gridBagConstraints);

        formFontPanel.setLayout(new java.awt.GridBagLayout());

        formFontPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Formularschrift", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
        formFontType.setModel(new javax.swing.DefaultComboBoxModel(getAvailableFonts()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        formFontPanel.add(formFontType, gridBagConstraints);

        formFontStyle.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"normal", "fett", "kursiv", "fett/kursiv"}));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        formFontPanel.add(formFontStyle, gridBagConstraints);

        formFontSize.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"8", "9", "10", "11", "12", "13", "14", "16", "18", "20", "22", "24"}));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        formFontPanel.add(formFontSize, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        formPanel.add(formFontPanel, gridBagConstraints);

        tableFontPanel.setLayout(new java.awt.GridBagLayout());

        tableFontPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Tabellenschrift", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
        tableFontType.setModel(new javax.swing.DefaultComboBoxModel(getAvailableFonts()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        tableFontPanel.add(tableFontType, gridBagConstraints);

        tableFontStyle.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"normal", "fett", "kursiv", "fett/kursiv"}));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        tableFontPanel.add(tableFontStyle, gridBagConstraints);

        tableFontSize.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"8", "9", "10", "11", "12", "13", "14", "16", "18", "20", "22", "24"}));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(1, 10, 1, 2);
        tableFontPanel.add(tableFontSize, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        formPanel.add(tableFontPanel, gridBagConstraints);

        previewPanel.setLayout(new java.awt.GridBagLayout());

        previewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Vorschau", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("The Quick Brown Fox Jumps Over The Lazy Dog!");
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        previewPanel.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        formPanel.add(previewPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(formPanel, gridBagConstraints);

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        buttonPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        buttonNestedPanel.setLayout(new java.awt.GridBagLayout());

        fontConfigAccept.setText("Speichern");
        fontConfigAccept.setMnemonic(KeyEvent.VK_S);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        buttonNestedPanel.add(fontConfigAccept, gridBagConstraints);

        fontConfigDecline.setText("Abbrechen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        buttonNestedPanel.add(fontConfigDecline, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        buttonPanel.add(buttonNestedPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(buttonPanel, gridBagConstraints);
    }// </editor-fold>


    // Variablendeklaration - nicht modifizieren
    private javax.swing.JPanel buttonNestedPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton fontConfigAccept;
    private javax.swing.JButton fontConfigDecline;
    private javax.swing.JPanel formFontPanel;
    private javax.swing.JComboBox formFontSize;
    private javax.swing.JComboBox formFontStyle;
    private javax.swing.JComboBox formFontType;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel labelFontPanel;
    private javax.swing.JComboBox labelFontSize;
    private javax.swing.JComboBox labelFontStyle;
    private javax.swing.JComboBox labelFontType;
    private javax.swing.JPanel previewPanel;
    private javax.swing.JPanel tableFontPanel;
    private javax.swing.JComboBox tableFontSize;
    private javax.swing.JComboBox tableFontStyle;
    private javax.swing.JComboBox tableFontType;
    // Ende der Variablendeklaration

    private String[] getAvailableFonts() {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        return ge.getAvailableFontFamilyNames();
    }

    public void actionPerformed(ActionEvent e) {
        Object obj = e.getSource();
        JComboBox box = (JComboBox) obj;
        String boxName = box.getName();
        if (boxName.equals("formFontType")) {
            jTextArea1.setFont(editableFontMap.get("FormFont"));
            newFont = new Font(box.getSelectedItem().toString(), this.getFontMap().get("FormFont").getStyle(), this.getFontMap().get("FormFont").getSize());
            jTextArea1.setFont(newFont);
            editableFontMap.remove("FormFont");
            editableFontMap.put("FormFont", newFont);
        } else if (boxName.equals("formFontStyle")) {
            jTextArea1.setFont(editableFontMap.get("FormFont"));
            newFont = new Font(editableFontMap.get("FormFont").getFontName(), box.getSelectedIndex(), editableFontMap.get("FormFont").getSize());
            jTextArea1.setFont(newFont);
            editableFontMap.remove("FormFont");
            editableFontMap.put("FormFont", newFont);
        } else if (boxName.equals("formFontSize")) {
            jTextArea1.setFont(editableFontMap.get("FormFont"));
            newFont = new Font(editableFontMap.get("FormFont").getFontName(), editableFontMap.get("FormFont").getStyle(), Integer.parseInt(box.getSelectedItem().toString()));
            jTextArea1.setFont(newFont);
            editableFontMap.remove("FormFont");
            editableFontMap.put("FormFont", newFont);
        } else if (boxName.equals("labelFontType")) {
            jTextArea1.setFont(editableFontMap.get("LabelFont"));
            newFont = new Font(box.getSelectedItem().toString(), editableFontMap.get("LabelFont").getStyle(), editableFontMap.get("LabelFont").getSize());
            jTextArea1.setFont(newFont);
            editableFontMap.remove("LabelFont");
            editableFontMap.put("LabelFont", newFont);
        } else if (boxName.equals("labelFontStyle")) {
            jTextArea1.setFont(editableFontMap.get("LabelFont"));
            newFont = new Font(editableFontMap.get("LabelFont").getFontName(), box.getSelectedIndex(), editableFontMap.get("LabelFont").getSize());
            jTextArea1.setFont(newFont);
            editableFontMap.remove("LabelFont");
            editableFontMap.put("LabelFont", newFont);
        } else if (boxName.equals("labelFontSize")) {
            jTextArea1.setFont(editableFontMap.get("LabelFont"));
            newFont = new Font(editableFontMap.get("LabelFont").getFontName(), editableFontMap.get("LabelFont").getStyle(), Integer.parseInt(box.getSelectedItem().toString()));
            jTextArea1.setFont(newFont);
            editableFontMap.remove("LabelFont");
            editableFontMap.put("LabelFont", newFont);
        } else if (boxName.equals("tableFontType")) {
            jTextArea1.setFont(editableFontMap.get("TableFont"));
            newFont = new Font(box.getSelectedItem().toString(), editableFontMap.get("TableFont").getStyle(), editableFontMap.get("TableFont").getSize());
            jTextArea1.setFont(newFont);
            editableFontMap.remove("TableFont");
            editableFontMap.put("TableFont", newFont);
        } else if (boxName.equals("tableFontStyle")) {
            jTextArea1.setFont(editableFontMap.get("TableFont"));
            newFont = new Font(editableFontMap.get("TableFont").getFontName(), box.getSelectedIndex(), editableFontMap.get("TableFont").getSize());
            jTextArea1.setFont(newFont);
            editableFontMap.remove("TableFont");
            editableFontMap.put("TableFont", newFont);
        } else if (boxName.equals("tableFontSize")) {
            jTextArea1.setFont(editableFontMap.get("TableFont"));
            newFont = new Font(editableFontMap.get("TableFont").getFontName(), editableFontMap.get("TableFont").getStyle(), Integer.parseInt(box.getSelectedItem().toString()));
            jTextArea1.setFont(newFont);
            editableFontMap.remove("TableFont");
            editableFontMap.put("TableFont", newFont);
        }
    }

    protected Map<String, Font> getNewFonts() {
        return editableFontMap;
    }

    protected void updateInternalMap() {
        editableFontMap = this.getFontMap();
    }
}

